const express = require('express');
const router = express.Router();
const upload = require('../middleware/upload');
const { verifyToken } = require('../middleware/auth');
const { createListing, getAllListings, getMyListings, updateListingStatus, deleteListing } = require('../controllers/listings.controller');
router.get('/', verifyToken, getAllListings);
router.get('/my', verifyToken, getMyListings);
router.post('/', verifyToken, upload.single('image'), createListing);
router.patch('/:id/status', verifyToken, updateListingStatus);
router.delete('/:id', verifyToken, deleteListing);
module.exports = router;
