const express = require('express');
const router = express.Router();
const multer = require('multer');
const path = require('path');
const { verifyToken, requireRole } = require('../middleware/auth');
const { createReport, previewReport, getMyReports, getAllReports, updateStatus } = require('../controllers/reports.controller');
const storage = multer.diskStorage({ destination: (req, file, cb) => cb(null, 'uploads/'), filename: (req, file, cb) => cb(null, Date.now() + path.extname(file.originalname)) });
const upload = multer({ storage });
router.post('/preview', verifyToken, upload.single('image'), previewReport);
router.post('/', verifyToken, upload.single('image'), createReport);
router.get('/my', verifyToken, getMyReports);
router.get('/', verifyToken, requireRole('admin'), getAllReports);
router.patch('/:id/status', verifyToken, requireRole('admin'), updateStatus);
module.exports = router;
